CREATE TABLE "access_codes" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"code"	TEXT NOT NULL UNIQUE,
	"claimed_by"	INTEGER DEFAULT NULL UNIQUE
);

CREATE TABLE "activity_records" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"user_id"	INTEGER NOT NULL,
	"step_count"	INTEGER NOT NULL,
	"duration"	INTEGER NOT NULL,
	"proof_filename"	TEXT NOT NULL
);

CREATE TABLE "users" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"username"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL
);
